config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only: [:create, :new, :destroy]
  resources :posts
  devise_for :users, controllers:{ registrations:'user_registrations/registrations'}
  resources :template_ones


  root to: 'template_ones#index'

  resources :posts do
    resources :comments
  end

  get 'edit_about', to: 'template_ones#edit_about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/template_one.rb
class TemplateOne < ApplicationRecord
  mount_uploader :about_image, PageImageUploader

  private

  FRONT_END_COLOUR = %w(
  red
  blue
  black
  green)
end

app/controllers/template_ones_controller.rb
class TemplateOnesController < ApplicationController
  before_action :set_template_one, only: [:show, :edit, :update, :destroy, :edit_about]
  before_action :authenticate_user!, except: [:show]
  before_action :not_admin_user, only: [ :edit, :update, :destroy]

  # GET /template_ones
  # GET /template_ones.json
  def index
    @template_ones = TemplateOne.all
  end

  # GET /template_ones/1
  # GET /template_ones/1.json
  def show

  end

  # GET /template_ones/new
  def new
    @template_one = TemplateOne.new
  end

  # GET /template_ones/1/edit
  def edit

  end

  # POST /template_ones
  # POST /template_ones.json
  def create
    @template_one = TemplateOne.new(template_one_params)

    respond_to do |format|
      if @template_one.save
        format.html { redirect_to @template_one, notice: 'Template one was successfully created.' }
        format.json { render :show, status: :created, location: @template_one }
      else
        format.html { render :new }
        format.json { render json: @template_one.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /template_ones/1
  # PATCH/PUT /template_ones/1.json
  def update
    respond_to do |format|
      if @template_one.update(template_one_params)
        format.html { redirect_back fallback_location: root_path, notice: 'Template one was successfully updated.' }
        format.json { render :show, status: :ok, location: @template_one }
      else
        format.html { render :edit }
        format.json { render json: @template_one.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /template_ones/1
  # DELETE /template_ones/1.json
  def destroy
    @template_one.destroy
    respond_to do |format|
      format.html { redirect_to template_ones_url, notice: 'Template one was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit_about

  end

  private
    # Use callbacks to share common setup or constraints between actions.
   def not_admin_user
      if !current_user.try(:admin) == true
        flash[:danger] = "The resource does not exist"
       redirect_to root_path
     end
   end

    def set_template_one
      @template_one = TemplateOne.find(1)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def template_one_params
      params.require(:template_one).permit(
          :about_show,
          :about_title,
          :about_text,
          :about_image,
          :front_end_colour
      )
    end
end

app/helpers/template_ones_helper.rb
module TemplateOnesHelper
end

app/views/template_ones/_form.html.erb
<% content_for :javascript_head do %>
<%= javascript_include_tag "template_ones_web_page" %>
<% end %>

<div class = "container-fluid">
  <h1 id = 'about_title'><%= @template_one.about_title %></h1>
</div>

<%= simple_form_for(@template_one) do |f| %>
  <div class="form-inputs">
    <%= f.input :about_show, label:"Show this module?" %>
<div class="row">
  <div class=""col-sm-3>
    <%= f.input :about_title, label:false %>
    <%= f.input :about_text, label:false %>
  </div>

</div>



    <%#= f.input :about_title, label:false %>
    <%#= f.input :about_text, label:false %>
    <label>Add custom image</label>
    <%= f.input :about_image, label:false, as: :file %>
<%= f.input :front_end_colour, collection: TemplateOne::FRONT_END_COLOUR, label:"web page colour scheme" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit , data: {disable_with: 'doing something...'}%>
    <%= link_to "Home", root_path, class: "btn btn-outline-success btn-sm pull-right"%>
  </div>
<% end %>
<br>
<script>
$('#template_one_about_title').keyup(function () {
$('#about_title').html($(this).val());
})
</script>

app/views/template_ones/edit.html.erb
<h1>Editing Template One</h1>

<%= render 'form', template_one: @template_one %>

<%= link_to 'Show', @template_one %> |
<%= link_to 'Back', template_ones_path %>

app/views/template_ones/edit_about.html.erb
<%= render 'template_ones/edit_partials/about' %>

app/views/template_ones/index.html.erb
<h1>Template Ones</h1>

<table>
  <thead>
    <tr>
      <th>Pages</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @template_ones.each do |template_one| %>
      <tr>
        <td><%= template_one.about_title %></td>
        <td><%= link_to 'Show', template_one %></td>
        <% if current_user.try(:admin) == true %>
          <td><%= link_to 'Edit', edit_template_one_path(template_one) %></td>
          <td><%= link_to 'Destroy', template_one, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.try(:admin) == true %>
  <%= link_to 'New Template One', new_template_one_path %>
<% end %>

app/views/template_ones/new.html.erb
<h1>New Template One</h1>

<%= render 'form', template_one: @template_one %>

<%= link_to 'Back', template_ones_path %>

app/views/template_ones/show.html.erb
<% if @template_one.front_end_colour == 'red' %>
  <%= stylesheet_link_tag 'themes/w3', media: 'all', 'data-turbolinks-track': 'reload' %>
  <% else %>
  <%= stylesheet_link_tag 'themes/bootstrap', media: 'all', 'data-turbolinks-track': 'reload' %>
  <% end %>
<div class = "container">
<p>
  <strong>This is my web page:</strong>
  <%= @template_one.about_title %>
  <% if @template_one.about_show == true %>
    <%= @template_one.about_text %>
    <%= image_tag @template_one.about_image_url() %>
    <% end %>
</p>
</div>


<%= link_to 'Edit', edit_template_one_path(@template_one) if current_user.try(:admin?) %> |
<%= link_to 'Back', template_ones_path %>