config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only: [:create, :new, :destroy]
  resources :posts
  devise_for :users, controllers:{ registrations:'user_registrations/registrations'}
  resources :template_ones


  root to: 'template_ones#index'

  resources :posts do
    resources :comments
  end

  get 'edit_about', to: 'template_ones#edit_about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/navigation/_navbar.html.erb
<div class = 'Container'>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "My App", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor03">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Posts", posts_path, class: "nav-link"  %>
      </li>
      <li class="nav-item">
        <%= link_to "Contact", new_contact_path, class: "nav-link"  %>
      </li>
        <li class="nav-item">
          <%= link_to "Templates", template_ones_path, class: "nav-link"  %>
        </li>
<!--      <li class="nav-item">-->
        <%#= link_to "Pages", edit_about_path, class: "nav-link"  %>
<!--      </li>-->
    </ul>
    <ul class="nav navbar-nav ml-auto">
      <% if !current_user %>
      <li class="nav-item">
        <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
      </li>
      <% else %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="download"><%= current_user.email %> <span class="caret"></span></a>
        <div class="dropdown-menu" aria-labelledby="download">
          <%= link_to 'Edit Profile', edit_user_registration_path, class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>

        </div>
      </li>
      <%end %>
    </ul>

  </div>
</nav>
</div>